[package]
authors.workspace = true
description       = "Assets precompile for EVM pallet."
edition.workspace = true
name              = "darwinia-precompile-assets"
readme            = "README.md"
version.workspace = true

[dependencies]
# frontier
fp-evm     = { workspace = true }
pallet-evm = { workspace = true }

# moonbeam
precompile-utils = { workspace = true }

# paritytech
frame-support = { workspace = true }
frame-system  = { workspace = true }
pallet-assets = { workspace = true }
sp-core       = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec" }
scale-info = { workspace = true, features = ["std"] }
sha3       = { workspace = true }

# moonbeam
precompile-utils = { workspace = true, features = ["std", "testing"] }

# paritytech
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-core          = { workspace = true, features = ["std"] }
sp-io            = { workspace = true, features = ["std"] }
sp-runtime       = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	# frontier
	"fp-evm/std",
	"pallet-evm/std",

	# moonbeam
	"precompile-utils/std",

	# paritytech
	"frame-support/std",
	"frame-system/std",
	"pallet-assets/std",
	"sp-std/std",
	"sp-core/std",
]

runtime-benchmarks = []
