[package]
authors = ["Xavier Lau <xavier@inv.cafe>"]
edition = "2021"
name    = "weight-checker"
version = "0.0.0"

[dependencies]
# crates.io
clap  = { version = "*", features = ["derive"] }
regex = { version = "*" }

[workspace]
exclude = []
