[package]
authors.workspace = true
description       = "Darwinia deposit mechanism implementation."
edition.workspace = true
name              = "darwinia-deposit"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec" }
scale-info = { workspace = true }

# darwinia
darwinia-staking-traits = { workspace = true }
dc-inflation            = { workspace = true }
dc-types                = { workspace = true }

# subtrate
frame-support    = { workspace = true }
frame-system     = { workspace = true }
pallet-timestamp = { workspace = true }
sp-runtime       = { workspace = true }
# polkadot-sdk optional
frame-benchmarking = { workspace = true, optional = true }
sp-std             = { workspace = true, optional = true }

[dev-dependencies]
# polkadot-sdk
pallet-assets   = { workspace = true, features = ["std"] }
pallet-balances = { workspace = true, features = ["std"] }
sp-io           = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"scale-info/std",

	# darwinia
	"darwinia-staking-traits/std",
	"dc-inflation/std",

	# subtrate
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"sp-runtime/std",
	"sp-std?/std",
	# polkadot-sdk optional
	"frame-benchmarking?/std",
]

runtime-benchmarks = [
	# darwinia
	"darwinia-staking-traits/runtime-benchmarks",

	# polkadot-sdk
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	# polkadot-sdk optional
	"frame-benchmarking/runtime-benchmarks",
	"sp-std",
]

try-runtime = [
	# polkadot-sdk
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-timestamp/try-runtime",
	"sp-runtime/try-runtime",
]
