[package]
authors.workspace = true
description       = "Darwinia parachain staking."
edition.workspace = true
name              = "darwinia-staking"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec" }
log        = { workspace = true }
scale-info = { workspace = true }

# darwinia
darwinia-staking-traits = { workspace = true }
dc-types                = { workspace = true }
# darwinia optional
darwinia-deposit = { workspace = true, optional = true }

# subtrate
frame-support     = { workspace = true }
frame-system      = { workspace = true }
pallet-authorship = { workspace = true }
pallet-session    = { workspace = true }
sp-runtime        = { workspace = true }
sp-std            = { workspace = true }
# substrate optional
frame-benchmarking = { workspace = true, optional = true }

[dev-dependencies]
# crates.io
pretty_env_logger = { version = "0.4" }

# darwinia
darwinia-deposit = { workspace = true, features = ["std"] }

# substrate
dc-inflation         = { workspace = true, features = ["std"] }
pallet-assets        = { workspace = true, features = ["runtime-benchmarks", "std"] }
pallet-balances      = { workspace = true, features = ["std"] }
pallet-session       = { workspace = true, features = ["std"] }
pallet-timestamp     = { workspace = true, features = ["std"] }
pallet-treasury      = { workspace = true, features = ["std"] }
sp-core              = { workspace = true, features = ["std"] }
sp-io                = { workspace = true, features = ["std"] }
substrate-test-utils = { workspace = true }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"log/std",
	"scale-info/std",

	# darwinia
	"darwinia-staking-traits/std",
	# darwinia optional
	"darwinia-deposit?/std",

	# subtrate
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-session/std",
	"sp-runtime/std",
	"sp-std/std",
	# substrate optional
	"frame-benchmarking?/std",
]

runtime-benchmarks = [
	# darwinia
	"darwinia-deposit",
	"darwinia-staking-traits/runtime-benchmarks",

	# substrate
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]

try-runtime = [
	# substrate
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authorship/try-runtime",
	"sp-runtime/try-runtime",
]
