[package]
authors.workspace = true
description       = "Darwinia parachain staking."
edition.workspace = true
name              = "darwinia-staking"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec" }
ethabi     = { workspace = true }
log        = { workspace = true }
scale-info = { workspace = true }

# darwinia
darwinia-ethtx-forwarder = { workspace = true }
darwinia-staking-traits  = { workspace = true }
dc-primitives            = { workspace = true }
# darwinia optional
darwinia-deposit = { workspace = true, optional = true }

# frontier
fp-evm = { workspace = true }

# subtrate
frame-support     = { workspace = true }
frame-system      = { workspace = true }
pallet-authorship = { workspace = true }
pallet-session    = { workspace = true }
pallet-timestamp  = { workspace = true }
sp-core           = { workspace = true }
sp-runtime        = { workspace = true }
sp-std            = { workspace = true }
# polkadot-sdk optional
frame-benchmarking = { workspace = true, optional = true }

[dev-dependencies]
# crates.io
pretty_env_logger = { version = "0.5" }

# darwinia
darwinia-deposit = { workspace = true, features = ["std"] }

# polkadot-sdk
dc-inflation         = { workspace = true, features = ["std"] }
pallet-balances      = { workspace = true, features = ["std"] }
pallet-session       = { workspace = true, features = ["std"] }
pallet-treasury      = { workspace = true, features = ["std"] }
sp-io                = { workspace = true, features = ["std"] }
substrate-test-utils = { workspace = true }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"ethabi/std",
	"log/std",
	"scale-info/std",

	# darwinia
	"darwinia-ethtx-forwarder/std",
	"darwinia-staking-traits/std",
	"dc-primitives/std",
	# darwinia optional
	"darwinia-deposit?/std",

	# frontier
	"fp-evm/std",

	# subtrate
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	# polkadot-sdk optional
	"frame-benchmarking?/std",
]

runtime-benchmarks = [
	# darwinia
	"darwinia-deposit",
	"darwinia-ethtx-forwarder/runtime-benchmarks",
	"darwinia-staking-traits/runtime-benchmarks",

	# polkadot-sdk
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]

try-runtime = [
	# darwinia
	"darwinia-ethtx-forwarder/try-runtime",
	# polkadot-sdk
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-authorship/try-runtime",
	"pallet-timestamp/try-runtime",
	"sp-runtime/try-runtime",
]
