[settings]
provider = "native"

[relaychain]
chain           = "rococo-local"
default_args    = ["--database=paritydb", "-lparachain=debug"]
default_command = "tmp/polkadot"

[[relaychain.nodes]]
name      = "alice"
validator = true
[[relaychain.nodes]]
name      = "bob"
validator = true

[[parachains]]
chain = "koi-genesis"
id    = 2105
[parachains.collator]
args     = ["--database=paritydb", "--force-authoring", "-lparachain=debug"]
command  = "tmp/darwinia"
name     = "C1"
rpc_port = 10000
[[parachains]]
chain = "koi-genesis"
id    = 2105
[parachains.collator]
args     = ["--database=paritydb", "--force-authoring", "-lparachain=debug"]
command  = "tmp/darwinia"
name     = "C2"
rpc_port = 10001
[[parachains]]
chain = "koi-genesis"
id    = 2105
[parachains.collator]
args     = ["--database=paritydb", "--force-authoring", "-lparachain=debug"]
command  = "tmp/darwinia"
name     = "C3"
rpc_port = 10002
