[[bin]]
name = "darwinia"
path = "src/main.rs"

[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node implementation in Rust"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.6.7"

[dependencies]
# crates
futures         = { version = "0.3.5" }
parity-util-mem = { version = "*", default-features = false, features = ["jemalloc-global"] }
# darwinia
darwinia-cli     = { path = "cli" }
darwinia-service = { path = "node/service" }

[dev-dependencies]
assert_cmd = { version = "1.0.1" }
nix        = { version = "0.18" }
tempfile   = { version = "3.1.0" }

[features]
default = ["darwinia-cli/wasmtime"]
dev     = [
	"darwinia-service/dev",
	"darwinia-cli/dev",
]

[workspace]
exclude = []
members = [
	"cli",
	"primitives",
	"rpc",
	"runtime/common",
	"runtime/crab",
	"node/service",
]

[badges]
maintenance = { status = "actively-developed" }

[profile.release]
# Darwinia runtime requires unwinding.
panic = "unwind"
