[profile.release]
panic = 'unwind'

[workspace]
members = [
    "core/basic-authorship",
    "core/chain-spec",
    "core/cli",
    "core/client",
    "core/client/db",
    "core/consensus/babe",
    "core/consensus/babe/primitives",
    "core/consensus/slots",
    "core/consensus/uncles",
    "core/ethash",
    "core/finality-grandpa",
#    "core/merkle-mountain-range",
    "core/merkle-patricia-trie",
#    "core/fly-client",
    "core/rpc",
    "core/service",
    "core/sr-eth-primitives",
    "core/test-client",
    "core/test-runtime",
    "core/test-runtime/client",

    "node/cli",
    "node/executor",
    "node/primitives",
    "node/rpc",
    "node/rpc-client",
    "node/runtime",

    "srml/babe",
    "srml/balances",
    "srml/contracts/rpc",
    "srml/eth-relay",
    "srml/eth-backing",
    "srml/im-online",
    "srml/kton",
    "srml/staking",
    "srml/support",
    "srml/system/rpc",
    "srml/transaction-payment/rpc",

    "test-utils/transaction-factory",
]
