[profile.release]
panic = 'unwind'

[workspace]
members = [
    "core/chain-spec",
    "core/cli",
    "core/ethash",
    "core/consensus/babe",
    "core/consensus/babe/primitives",
    "core/finality-grandpa",
    "core/consensus/slots",
#    "core/merkle-mountain-range",
    "core/merkle-patricia-trie",
#    "core/fly-client",
    "core/service",
    "core/sr-eth-primitives",
    "core/test-client",
    "core/test-runtime",
    "core/test-runtime/client",

    "node/cli",
    "node/executor",
    "node/primitives",
    "node/rpc",
    "node/rpc-client",
    "node/runtime",

    "srml/babe",
    "srml/balances",
    "srml/eth-relay",
    "srml/eth-backing",
    "srml/im-online",
    "srml/kton",
    "srml/staking",
    "srml/support",

    "test-utils/transaction-factory",
]
