[config]
default_to_workspace = false

[env]
WASM_BUILD_WORKSPACE_HINT = "${CARGO_MAKE_WORKING_DIRECTORY}"

[tasks.check]
args    = ["check"]
command = "cargo"
env     = { "SKIP_WASM_BUILD" = "1" }

[tasks.clippy]
args    = ["clippy"]
command = "cargo"
env     = { "SKIP_WASM_BUILD" = "1" }

[tasks.common-build]
args = [
	"--features",
	"--locked",
	"--no-default-features",
	"--release",
	"-p",
	"@@split(FEATURES, )",
	"build",
	"darwinia",
]
[tasks.common-run]
args = [
	"--alice",
	"--collator",
	"--rpc-cors",
	"--rpc-methods",
	"--tmp",
	"--unsafe-rpc-external",
	"--unsafe-ws-external",
	"@@split(FLAGS, )",
	"all",
	"unsafe",
]

[tasks.build-darwinia]
command = "cargo"
env     = { "FEATURES" = "darwinia-native" }
extend  = "common-build"
[tasks.cbuild-darwinia]
command = "cross"
env     = { "FEATURES" = "darwinia-native" }
extend  = "common-build"
[tasks.run-darwinia]
command = "target/release/darwinia"
env     = { "FLAGS" = "--chain darwinia-dev" }
extend  = "common-run"

[tasks.build-crab]
command = "cargo"
env     = { "FEATURES" = "crab-native" }
extend  = "common-build"
[tasks.cbuild-crab]
command = "cross"
env     = { "FEATURES" = "crab-native" }
extend  = "common-build"
[tasks.run-crab]
command = "target/release/darwinia"
env     = { "FLAGS" = "--chain crab-dev" }
extend  = "common-run"

[tasks.build-koi]
command = "cargo"
env     = { "FEATURES" = "koi-native" }
extend  = "common-build"
[tasks.cbuild-koi]
command = "cross"
env     = { "FEATURES" = "koi-native" }
extend  = "common-build"
[tasks.run-koi]
command = "target/release/darwinia"
env     = { "FLAGS" = "--chain koi-dev" }
extend  = "common-run"

# Build for runtime benchmarks.
[tasks.build-bench]
command = "cargo"
env     = { "FEATURES" = "all-natives,runtime-benchmarks" }
extend  = "common-build"
[tasks.cbuild-bench]
command = "cross"
env     = { "FEATURES" = "all-natives,runtime-benchmarks" }
extend  = "common-build"

# Build for try runtime.
[tasks.build-trt]
command = "cargo"
env     = { "FEATURES" = "all-natives,try-runtime" }
extend  = "common-build"
[tasks.cbuild-trt]
command = "cross"
env     = { "FEATURES" = "all-natives,try-runtime" }
extend  = "common-build"

# Build for all runtimes.
[tasks.build-ar]
command = "cargo"
env     = { "FEATURES" = "all-natives" }
extend  = "common-build"
[tasks.cbuild-ar]
command = "cross"
env     = { "FEATURES" = "all-natives" }
extend  = "common-build"

# Build for testnets.
[tasks.build-tns]
command = "cargo"
env     = { "FEATURES" = "koi-native" }
extend  = "common-build"
[tasks.cbuild-tns]
command = "cross"
env     = { "FEATURES" = "koi-native" }
extend  = "common-build"

# Build for mainnets.
[tasks.build-mns]
command = "cargo"
env     = { "FEATURES" = "crab-native,darwinia-native" }
extend  = "common-build"
[tasks.cbuild-mns]
command = "cross"
env     = { "FEATURES" = "crab-native,darwinia-native" }
extend  = "common-build"

[tasks.build-all]
args    = ["--all-features", "--locked", "--release", "build"]
command = "cargo"
[tasks.cbuild-all]
args    = ["--all-features", "--locked", "--release", "build"]
command = "cross"
