[package]
authors.workspace = true
description       = "Staking precompile for EVM pallet."
edition.workspace = true
name              = "darwinia-precompile-staking"
readme            = "README.md"
version.workspace = true

[dependencies]
# frontier
fp-evm     = { workspace = true }
pallet-evm = { workspace = true }

# darwinia
darwinia-staking = { workspace = true }

# moonbeam
precompile-utils = { workspace = true }

# substrate
frame-support = { workspace = true }
frame-system  = { workspace = true }
sp-core       = { workspace = true }
sp-runtime    = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec", features = ["std"] }
scale-info = { workspace = true, features = ["std"] }

# darwinia
darwinia-deposit = { workspace = true, features = ["std"] }

# moonbeam
precompile-utils = { workspace = true, features = ["std", "testing"] }

# substrate
frame-system     = { workspace = true, features = ["std"] }
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-io            = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	# frontier
	"fp-evm/std",
	"pallet-evm/std",

	# darwinia
	"darwinia-staking/std",

	# moonbeam
	"precompile-utils/std",

	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]

runtime-benchmarks = [
	# darwinia
	"darwinia-staking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
