[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node rpc"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-rpc"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.9.5"

[dependencies]
# crates
codec        = { package = "parity-scale-codec", version = "1.3.5", default-features = false }
jsonrpc-core = { version = "15.1.0" }
# darwinia frame
darwinia-balances-rpc   = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "1.3.3" }
darwinia-header-mmr-rpc = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "1.3.3" }
darwinia-staking-rpc    = { git = "https://github.com/darwinia-network/darwinia-common.git", tag = "1.3.3" }
# darwinia primitives
darwinia-primitives = { path = "../primitives" }
# substrate client
sc-chain-spec           = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sc-client-api           = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sc-consensus-babe       = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sc-consensus-babe-rpc   = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sc-consensus-epochs     = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sc-finality-grandpa     = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sc-finality-grandpa-rpc = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sc-rpc                  = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sc-sync-state-rpc       = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
# substrate frame
pallet-transaction-payment-rpc = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
substrate-frame-rpc-system     = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
# substrate primitives
sp-api              = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sp-block-builder    = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sp-blockchain       = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sp-consensus        = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sp-consensus-babe   = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sp-keystore         = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sp-runtime          = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
sp-transaction-pool = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.1.0-darwinia" }
