[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node rpc"
edition     = "2021"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "darwinia-rpc"
repository  = "https://github.com/darwinia-network/darwinia"
version     = "0.11.8"

[dependencies]
# crates.io
code           = { package = "parity-scale-codec", version = "2.1", default-features = false }
jsonrpc-core   = { version = "18.0" }
jsonrpc-pubsub = { version = "18.0" }
# darwinia-network frame
darwinia-balances-rpc   = { git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.0" }
darwinia-fee-market-rpc = { git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.0" }
darwinia-header-mmr-rpc = { git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.0" }
darwinia-staking-rpc    = { git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.0" }
dc-db                   = { git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.0" }
dc-rpc                  = { features = ["rpc_binary_search_estimate"], git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.0" }
# dp-rpc                  = { git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.0" }
dvm-ethereum            = { git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.0" }
dvm-rpc-runtime-api     = { git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.0" }
# darwinia-network primitives
crab-runtime               = { path = "../runtime/crab" }
darwinia-common-primitives = { path = "../primitives/common" }
# paritytech client
sc-chain-spec           = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-client-api           = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-consensus-babe       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-consensus-babe-rpc   = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-consensus-epochs     = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-finality-grandpa     = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-finality-grandpa-rpc = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-rpc                  = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-sync-state-rpc       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sc-transaction-pool-api = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
# paritytech frame
pallet-transaction-payment-rpc = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
substrate-frame-rpc-system     = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
# paritytech primitives
sc-network        = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-api            = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-block-builder  = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-blockchain     = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-consensus      = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-consensus-babe = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-keystore       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
sp-runtime        = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.0" }
