[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node service"
edition     = "2021"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "darwinia-node-service"
repository  = "https://github.com/darwinia-network/darwinia"
version     = "1.0.0"

[dependencies]
# crates.io
array-bytes = { version = "4.1" }
futures     = { version = "0.3" }
log         = { version = "0.4" }
serde       = { version = "1.0", features = ["derive"] }
tokio       = { version = "1.17" }
# darwinia-network primitives
darwinia-primitives = { path = "../../primitives" }
# darwinia-network rpc
darwinia-rpc = { path = "../../rpc" }
# darwinia-network runtime
crab-runtime     = { path = "../../runtime/crab" }
darwinia-runtime = { path = "../../runtime/darwinia" }
# darwinia-network evm
dp-evm-trace-ext              = { git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.12.5" }
fc-db                         = { git = "https://github.com/darwinia-network/frontier", branch = "darwinia-v0.12.5" }
fc-mapping-sync               = { git = "https://github.com/darwinia-network/frontier", branch = "darwinia-v0.12.5" }
fc-rpc                        = { features = ["rpc_binary_search_estimate"], git = "https://github.com/darwinia-network/frontier", branch = "darwinia-v0.12.5" }
fc-rpc-core                   = { git = "https://github.com/darwinia-network/frontier", branch = "darwinia-v0.12.5" }
fp-rpc                        = { git = "https://github.com/darwinia-network/frontier", branch = "darwinia-v0.12.5" }
moonbeam-rpc-debug            = { git = "https://github.com/darwinia-network/moonbeam", branch = "darwinia-v0.12.5" }
moonbeam-rpc-primitives-debug = { git = "https://github.com/darwinia-network/moonbeam", branch = "darwinia-v0.12.5" }
moonbeam-rpc-trace            = { git = "https://github.com/darwinia-network/moonbeam", branch = "darwinia-v0.12.5" }
# frontier primitives
fp-evm = { git = "https://github.com/darwinia-network/frontier", branch = "darwinia-v0.12.5" }
# paritytech client
sc-authority-discovery = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-basic-authorship    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-chain-spec          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-client-api          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-consensus           = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-consensus-babe      = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-consensus-slots     = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-executor            = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-finality-grandpa    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-network             = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-service             = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-sync-state-rpc      = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-telemetry           = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sc-transaction-pool    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
# paritytech frame
frame-benchmarking                         = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
frame-system-rpc-runtime-api               = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
pallet-im-online                           = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
substrate-prometheus-endpoint              = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
# paritytech primitives
sp-api                 = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-authority-discovery = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-block-builder       = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-blockchain          = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-consensus           = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-consensus-babe      = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-core                = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-finality-grandpa    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-offchain            = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-runtime             = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-session             = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-timestamp           = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-transaction-pool    = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }
sp-trie                = { git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.12.5" }

[features]
default = [
	"db",
	"full-node",
]

db = ["sc-service/db"]

full-node = []

fast-runtime = [
	"crab-runtime/fast-runtime",
	"darwinia-runtime/fast-runtime",
]

evm-tracing = [
	"crab-runtime/evm-tracing",
	"darwinia-runtime/evm-tracing",
]

runtime-benchmarks = [
	"crab-runtime/runtime-benchmarks",
	"darwinia-runtime/runtime-benchmarks",
]

try-runtime = [
	"crab-runtime/try-runtime",
	"darwinia-runtime/try-runtime",
]
