[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
jsonrpc-core = "14.0.3"

#client = { package = "substrate-client", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
client = { package = "substrate-client", path = "../../core/client" }
sr-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
#srml-contracts-rpc = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
srml-contracts-rpc = { path = "../../srml/contracts/rpc" }
#srml-transaction-payment-rpc = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
srml-transaction-payment-rpc = { path = "../../srml/transaction-payment/rpc" }
#srml-system-rpc = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
srml-system-rpc = { path = "../../srml/system/rpc" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }

node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }
