[package]
name = "node-cli"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node implementation in Rust"
build = "build.rs"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"
default-run = "darwinia"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[badges]
travis-ci = { repository = "darwinia-network/darwinia", branch = "develop" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "darwinia-network/darwinia" }
is-it-maintained-open-issues = { repository = "darwinia-network/darwinia" }

[[bin]]
name = "darwinia"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.0.6" }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
jsonrpc-core = "14.0.3"
log = "0.4.8"
rand = "0.7.2"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.48"
structopt = { version = "0.3.8", optional = true }
tracing = "0.1.10"

# primitives
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

sp-authority-discovery = {  git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-consensus = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-consensus-babe = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-core = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-finality-tracker = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-inherents = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-io = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-keyring = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-runtime = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-timestamp = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

# client dependencies
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

sc-authority-discovery = {  git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-basic-authorship = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-chain-spec = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-client = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-client-api = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-client-db = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-consensus-babe = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-network = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-offchain = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-rpc = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-service = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-telemetry = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-tracing = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-transaction-pool = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

sp-transaction-pool = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

# frame dependencies
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
frame-system = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

pallet-authority-discovery = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
pallet-contracts = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
pallet-im-online = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
pallet-indices = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
pallet-timestamp = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

pallet-claims = { package = "darwinia-claims", path = "../../../frame/claims" }

# node-specific dependencies
node-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

node-executor = { path = "../executor" }
node-rpc = { path = "../rpc" }
node-runtime = { path = "../runtime" }

# CLI-specific dependencies
frame-benchmarking-cli = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

node-inspect = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
node-transaction-factory = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

sc-cli = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

# TODO https://github.com/darwinia-network/darwinia/issues/26
#sc-cli = { package = "darwinia-cli", optional = true, path = "../../../client/cli" }

# WASM-specific dependencies
browser-utils = { package = "substrate-browser-utils", optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }

[dev-dependencies]
assert_cmd = "0.12"
futures = "0.3.1"
nix = "0.17"
tempfile = "3.1.0"

sc-consensus-babe = { features = ["test-helpers"], git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-consensus-epochs = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-keystore = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-service-test = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

[build-dependencies]
structopt = { version = "0.3.8", optional = true }
vergen = { version = "3.0.4", optional =true }

build-script-utils = { package = "substrate-build-script-utils", git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
frame-benchmarking-cli = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

sc-cli = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

# TODO https://github.com/darwinia-network/darwinia/issues/26
#sc-cli = { package = "darwinia-cli", optional = true, path = "../../../client/cli" }

node-inspect = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
node-transaction-factory = { optional = true, git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

[features]
default = ["cli", "wasmtime"]
browser = [
	"browser-utils",

	"wasm-bindgen",
	"wasm-bindgen-futures",
]
cli = [
	"frame-benchmarking-cli",

	"node-executor/wasmi-errno",
	"node-inspect",
	"node-transaction-factory",

	"sc-cli",
	"sc-service/rocksdb",

	"structopt",
	"vergen",
]
wasmtime = [
	"cli",

	"node-executor/wasmtime",

	"sc-cli/wasmtime",
	"sc-service/wasmtime",
]
