[package]
name = "substrate-consensus-babe"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "BABE consensus algorithm for substrate"
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", features = ["derive"] }
#babe_primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
babe_primitives = { package = "substrate-consensus-babe-primitives", path = "./primitives" }
primitives = { package = "substrate-primitives", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
app-crypto = { package = "substrate-application-crypto", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
num-bigint = "0.2.3"
num-rational = "0.2.2"
num-traits = "0.2.8"
runtime-support = { package = "srml-support", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
runtime-version = { package = "sr-version", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
runtime-io = { package = "sr-io", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
inherents = { package = "substrate-inherents", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
substrate-telemetry = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
keystore = { package = "substrate-keystore", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
#srml-babe = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
srml-babe = { path = "../../../srml/babe" }
client = { package = "substrate-client", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
#client = { package = "substrate-client", path = "../../client" }
sr-api = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
block-builder-api = { package = "substrate-block-builder-runtime-api", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
header-metadata = { package = "substrate-header-metadata", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
consensus-common = { package = "substrate-consensus-common", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
uncles = { package = "substrate-consensus-uncles", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
#slots = { package = "substrate-consensus-slots", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop"  }
slots = { package = "substrate-consensus-slots", path = "../slots"  }
sr-primitives = {  git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
fork-tree = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop" }
futures-preview = { version = "0.3.0-alpha.19", features = ["compat"] }
futures01 = { package = "futures", version = "0.1" }
futures-timer = "0.4.0"
parking_lot = "0.9.0"
log = "0.4.8"
schnorrkel = { version = "0.8.5", features = ["preaudit_deprecated"] }
rand = "0.7.2"
merlin = "1.2.1"
pdqselect = "0.1.0"
derive_more = "0.15.0"

[features]
test-helpers = []
