[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node common runtime"
edition     = "2021"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "darwinia-common-runtime"
repository  = "https://github.com/darwinia-network/darwinia"
version     = "0.11.7"

[dependencies]
# crates.io
codec             = { package = "parity-scale-codec", version = "2.1", default-features = false }
static_assertions = { version = "1.1" }
# darwinia-network frame
darwinia-balances = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.11.7" }
darwinia-support  = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "darwinia-v0.11.7" }
# darwinia-network primitives
darwinia-common-primitives = { default-features = false, path = "../../primitives/common" }
# paritytech frame
frame-support              = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
frame-system               = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
pallet-authorship          = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
pallet-treasury            = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
# paritytech primitives
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }
sp-std     = { default-features = false, git = "https://github.com/darwinia-network/substrate", branch = "darwinia-v0.11.7" }

[features]
default = ["std"]

no_std = []
std = [
	# crates.io
	"codec/std",
	# darwinia-network frame
	"darwinia-balances/std",
	"darwinia-support/std",
	# darwinia-network primitives
	"darwinia-common-primitives/std",
	# paritytech frame
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	# paritytech primitives
	"sp-runtime/std",
	"sp-std/std",
]
