[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node runtime common"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-runtime-common"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.9.5"

[dependencies]
# crates
codec             = { package = "parity-scale-codec", version = "1.3.5", default-features = false }
static_assertions = { version = "1.1.0" }
# darwinia frame
darwinia-balances = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common.git", rev = "3a7f1ec93aecf4bced73e769cc9138db309fa29e" }
darwinia-staking  = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common.git", rev = "3a7f1ec93aecf4bced73e769cc9138db309fa29e" }
darwinia-support  = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common.git", rev = "3a7f1ec93aecf4bced73e769cc9138db309fa29e" }
# darwinia primitives
darwinia-primitives = { default-features = false, path = "../../primitives" }
# substrate frame
frame-support              = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "668ecade60abe5a644868aefd3d231c9839fe652" }
frame-system               = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "668ecade60abe5a644868aefd3d231c9839fe652" }
pallet-authorship          = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "668ecade60abe5a644868aefd3d231c9839fe652" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "668ecade60abe5a644868aefd3d231c9839fe652" }
# substrate primitives
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "668ecade60abe5a644868aefd3d231c9839fe652" }
sp-std     = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", rev = "668ecade60abe5a644868aefd3d231c9839fe652" }

[features]
default = ["std"]

no_std = []
std    = [
	"crates-std",
	"darwinia-frame-std",
	"darwinia-primitives-std",
	"substrate-frame-std",
	"substrate-primitives-std",
]

crates-std               = ["codec/std"]
darwinia-frame-std       = [
	"darwinia-balances/std",
	"darwinia-staking/std",
	"darwinia-support/std",
]
darwinia-primitives-std  = ["darwinia-primitives/std"]
substrate-frame-std      = [
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-transaction-payment/std",
]
substrate-primitives-std = [
	"sp-runtime/std",
	"sp-std/std",
]
