[package]
authors.workspace = true
description       = "Darwinia Common Runtime"
edition.workspace = true
name              = "dr-common"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec" }
log        = { workspace = true }
scale-info = { workspace = true }
smallvec   = { version = "1.10" }

# darwinia
dc-primitives = { workspace = true }
dpc-assets    = { workspace = true }

# frontier
pallet-evm = { workspace = true }

# polkadot
xcm          = { workspace = true }
xcm-builder  = { workspace = true }
xcm-executor = { workspace = true }

# substrate
frame-support     = { workspace = true }
frame-system      = { workspace = true }
pallet-assets     = { workspace = true, optional = true }
pallet-authorship = { workspace = true }
pallet-balances   = { workspace = true }
pallet-collective = { workspace = true }
sp-core           = { workspace = true }
sp-io             = { workspace = true }
sp-runtime        = { workspace = true }
sp-std            = { workspace = true }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"log/std",
	"scale-info/std",

	# darwinia
	"dc-primitives/std",
	"dpc-assets/std",

	# frontier
	"pallet-evm/std",

	# polkadot
	"xcm-builder/std",
	"xcm-executor/std",
	"xcm/std",

	# substrate
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-collective/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	# substrate optional
	"pallet-assets?/std",
]

test = []

runtime-benchmarks = [
	"pallet-assets/runtime-benchmarks",
]
