[package]
authors.workspace = true
description       = "Darwinia Common Runtime"
edition.workspace = true
name              = "darwinia-common-runtime"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec" }
log        = { workspace = true }
scale-info = { workspace = true }
smallvec   = { version = "1.10" }

# darwinia
darwinia-precompile-assets = { workspace = true }
dc-primitives              = { workspace = true }

# frontier
fp-account = { workspace = true }
pallet-evm = { workspace = true }

# polkadot-sdk
cumulus-primitives-core = { workspace = true }
frame-support           = { workspace = true }
frame-system            = { workspace = true }
pallet-assets           = { workspace = true, optional = true }
pallet-authorship       = { workspace = true }
pallet-balances         = { workspace = true }
pallet-collective       = { workspace = true }
pallet-message-queue    = { workspace = true }
sp-core                 = { workspace = true }
sp-io                   = { workspace = true }
sp-runtime              = { workspace = true }
sp-std                  = { workspace = true }
xcm                     = { workspace = true }
xcm-executor            = { workspace = true }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"log/std",
	"scale-info/std",

	# darwinia
	"darwinia-precompile-assets/std",
	"dc-primitives/std",

	# frontier
	"fp-account/std",
	"pallet-evm/std",

	# polkadot-sdk
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-balances/std",
	"pallet-collective/std",
	"pallet-message-queue/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-executor/std",
	"xcm/std",
	# polkadot-sdk optional
	"pallet-assets?/std",
]

test = []

runtime-benchmarks = [
	# polkadot-sdk
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-collective/runtime-benchmarks",
	"pallet-message-queue/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	# polkadot-sdk optional
	"pallet-assets/runtime-benchmarks",
]
