[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node runtime common"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-runtime-common"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.11.5"

[dependencies]
# crates.io
codec             = { package = "parity-scale-codec", version = "2.1", default-features = false }
static_assertions = { version = "1.1" }
# darwinia-network frame
darwinia-balances = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", tag = "darwinia-v0.11.6-1" }
darwinia-staking  = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", tag = "darwinia-v0.11.6-1" }
darwinia-support  = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", tag = "darwinia-v0.11.6-1" }
# darwinia-network primitives
darwinia-primitives = { default-features = false, path = "../../primitives" }
# paritytech frame
frame-support              = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
frame-system               = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
pallet-authorship          = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
pallet-transaction-payment = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
pallet-treasury            = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
# paritytech primitives
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
sp-std     = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }

# will be removed in later substrate version
max-encoded-len = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }

[features]
default = ["std"]

no_std = []
std = [
	# crates.io
	"codec/std",
	# darwinia-network frame
	"darwinia-balances/std",
	"darwinia-staking/std",
	"darwinia-support/std",
	# darwinia-network primitives
	"darwinia-primitives/std",
	# paritytech frame
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-transaction-payment/std",
	"pallet-treasury/std",
	# paritytech primitives
	"sp-runtime/std",
	"sp-std/std",
	"max-encoded-len/std",
]
