[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node runtime bridge primitives"
edition     = "2018"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "bridge-primitives"
repository  = "https://github.com/darwinia-network/darwinia"
version     = "0.11.6"

[dependencies]
# darwinia-network frame
darwinia-fee-market = { default-features = false, git = "https://github.com/darwinia-network/darwinia-common", branch = "bump-deps" }
# darwinia-network primitives
common-primitives = { default-features = false, path = "../common" }
# paritytech bridge frame
pallet-bridge-dispatch = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", tag = "darwinia-v0.11.6-4" }
# paritytech bridge primitives
bp-messages           = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", tag = "darwinia-v0.11.6-4" }
bp-runtime            = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", tag = "darwinia-v0.11.6-4" }
bridge-runtime-common = { default-features = false, git = "https://github.com/darwinia-network/parity-bridges-common", tag = "darwinia-v0.11.6-4" }
# paritytech frame
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
# paritytech primitives
sp-api     = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
sp-core    = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
sp-std     = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }

[features]
default = ["std"]

std = [
	# darwinia-network frame
	"darwinia-fee-market/std",
	# darwinia-network primitives
	"common-primitives/std",
	# paritytech bridge frame
	"pallet-bridge-dispatch/std",
	# paritytech bridge primitives
	"bp-messages/std",
	"bp-runtime/std",
	"bridge-runtime-common/std",
	# paritytech frame
	"frame-support/std",
	# paritytech primitives
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
]
