[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node runtime bridge primitives"
edition     = "2018"
homepage    = "https://darwinia.network"
license     = "GPL-3.0"
name        = "bridge-primitives"
repository  = "https://github.com/darwinia-network/darwinia"
version     = "0.11.6"

[dependencies]
# darwinia-network primitives
common-primitives = { default-features = false, path = "../common" }
# paritytech primitives
sp-core    = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate", tag = "darwinia-v0.11.6-1" }

[features]
default = ["std"]

std = [
	# darwinia-network primitives
	"common-primitives/std",
	# paritytech primitives
	"sp-core/std",
	"sp-runtime/std",
]
