[package]
authors.workspace = true
description       = "Arkworks BLS12-381 based precompile for EVM pallet."
edition.workspace = true
name              = "dpc-bls12-381"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
ark-bls12-381 = { version = "0.4.0", default-features = false, features = ["curve"] }
ark-ec        = { version = "0.4.1", default-features = false }
ark-ff        = { version = "0.4.1", default-features = false }
ark-serialize = { version = "0.4.1", default-features = false, features = ["derive"] }
sha2          = { version = "0.10.6", default-features = false }

# frontier
fp-evm     = { workspace = true }
pallet-evm = { workspace = true }

# moonbeam
precompile-utils = { workspace = true }

# substrate
frame-support = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
ark-std = { version = "0.4.0" }
rand    = { version = "0.8.5" }

[features]
default = ["std"]
std = [
	# crates.io
	"ark-bls12-381/std",
	"ark-ec/std",
	"ark-ff/std",
	"ark-serialize/std",
	"sha2/std",

	# frontier
	"fp-evm/std",
	"pallet-evm/std",

	# moonbeam
	"precompile-utils/std",

	# substrate
	"frame-support/std",
	"sp-std/std",
]
