[package]
authors     = ["Darwinia Network <hello@darwinia.network>"]
build       = "build.rs"
description = "Darwinia Client Node"
edition     = "2018"
homepage    = "https://darwinia.network/"
license     = "GPL-3.0"
name        = "darwinia-cli"
repository  = "https://github.com/darwinia-network/darwinia/"
version     = "0.6.6"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# crates
log                  = { version = "0.4.11" }
serde                = { version = "1.0.115", optional = true }
structopt            = { version = "0.3.16" }
tokio                = { version = "0.2.22", features = ["rt-threaded"], optional = true }
toml                 = { version = "0.5.6", optional = true }
wasm-bindgen         = { version = "0.2.67", optional = true }
wasm-bindgen-futures = { version = "0.4.17", optional = true }
# darwinia client
darwinia-cli = { optional = true, git = "https://github.com/darwinia-network/darwinia-common.git", branch = "master" }
# darwinia service
darwinia-service = { default-features = false, path = "../service" }
# substrate client
sc-cli        = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }
sc-client-api = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }
sc-executor   = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }
sc-network    = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }
sc-service    = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }
sc-tracing    = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }
# substrate primitives
sp-core = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }
# substrate utils
substrate-browser-utils = { optional = true, git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/darwinia-network/substrate.git", tag = "v2.0.0-rc.darwinia.4" }

[features]
default = [
	"cli",
	"db",
]

cli = [
	"serde",
	"tokio",
	"toml",
	"sc-cli",
	"sc-network",
	"sc-tracing",
	"darwinia-cli",
	"darwinia-service/full-node",
]
db  = ["darwinia-service/db"]

browser  = [
	"wasm-bindgen",
	"wasm-bindgen-futures",
	"substrate-browser-utils",
]
wasmtime = ["sc-cli/wasmtime"]

dev = ["darwinia-service/dev"]
