[package]
authors.workspace = true
description       = "Deposit precompile for EVM pallet."
edition.workspace = true
name              = "darwinia-precompile-deposit"
readme            = "README.md"
version.workspace = true

[dependencies]
# frontier
fp-evm     = { workspace = true }
pallet-evm = { workspace = true }

# darwinia
darwinia-deposit = { workspace = true }

# moonbeam
precompile-utils = { workspace = true }

# polkadot-sdk
frame-support = { workspace = true }
frame-system  = { workspace = true }
sp-core       = { workspace = true }
sp-runtime    = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
# crates.io
codec      = { workspace = true, features = ["std"] }
scale-info = { workspace = true, features = ["std"] }

# moonbeam
precompile-utils = { workspace = true, features = ["std", "testing"] }

# polkadot-sdk
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-io            = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	# frontier
	"fp-evm/std",
	"pallet-evm/std",

	# darwinia
	"darwinia-deposit/std",

	# moonbeam
	"precompile-utils/std",

	# polkadot-sdk
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
