[package]
authors.workspace = true
description       = "LCMP evm message execution."
edition.workspace = true
name              = "darwinia-message-transact"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec" }
ethereum   = { workspace = true }
scale-info = { workspace = true }

# frontier
fp-ethereum = { workspace = true }
fp-evm      = { workspace = true }
pallet-evm  = { workspace = true }

# substrate
frame-support = { workspace = true }
frame-system  = { workspace = true }
sp-core       = { workspace = true }
sp-runtime    = { workspace = true }
sp-std        = { workspace = true }

[dev-dependencies]
array-bytes  = { workspace = true }
libsecp256k1 = { workspace = true, features = ["std"] }
rlp          = { version = "0.5" }
sha3         = { workspace = true }

# frontier
fp-self-contained = { workspace = true, features = ["std"] }
pallet-ethereum   = { workspace = true, features = ["std"] }

# substrate
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }
sp-io            = { workspace = true, features = ["std"] }
sp-runtime       = { workspace = true, features = ["std"] }

[features]
default = ["std"]
std = [
	# crates.io
	"codec/std",
	"ethereum/std",
	"scale-info/std",

	# frontier
	"fp-ethereum/std",
	"fp-evm/std",
	"pallet-evm/std",

	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]

runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
]

try-runtime = [
	# substrate
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-evm/try-runtime",
	"sp-runtime/try-runtime",
]
