[package]
name = "node-executor"
version = "0.5.0"
authors = ["Darwinia Network <hello@darwinia.network>"]
description = "Darwinia node executor"
edition = "2018"
license = "GPL-3.0"
homepage = "https://darwinia.network/"
repository = "https://github.com/darwinia-network/darwinia/"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.16.0"

# github.com
# TODO benchmarking
#frame-benchmarking = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

node-primitives = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

sp-core = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sc-executor = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-io = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-state-machine = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
sp-trie = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }

# darwinia
node-runtime = { path = "../runtime" }

# TODO benchmarking
#[dev-dependencies]
#criterion = "0.3.0"
#wabt = "0.9.2"
#
#frame-support = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#frame-system = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#
#pallet-balances = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#pallet-contracts = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#pallet-grandpa = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#pallet-im-online = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#pallet-indices = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#pallet-session = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#pallet-timestamp = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#pallet-transaction-payment = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#pallet-treasury = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#
#sp-application-crypto = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#sp-runtime = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#
#substrate-test-client = { git = "https://github.com/darwinia-network/substrate.git", branch = "denny_support_mmr_header" }
#
#node-testing = { path = "../testing" }

[features]
wasmtime = [
	"sc-executor/wasmtime",
]
wasmi-errno = [
	"sc-executor/wasmi-errno",
]
stress-test = []

# TODO benchmarking
#[[bench]]
#name = "bench"
#harness = false
