[package]
authors.workspace = true
description       = "Darwinia asset limit implementation."
edition.workspace = true
name              = "darwinia-asset-limit"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { workspace = true }
scale-info = { workspace = true }

# moonbeam
pallet-asset-manager = { workspace = true }

# polkadot-sdk
frame-support = { workspace = true }
frame-system  = { workspace = true }

[features]
default = ["std"]

std = [
    # crates.io
    "codec/std",
    "scale-info/std",
    # moonbeam
    "pallet-asset-manager/std",
    # polkadot-sdk
    "frame-support/std",
    "frame-system/std",
]

try-runtime = [
    # moonbeam
    "pallet-asset-manager/try-runtime",
    # polkadot-sdk
    "frame-support/try-runtime",
    "frame-system/try-runtime",
]
