[package]
name = "substrate-consensus-babe-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for BABE consensus"
edition = "2018"

[dependencies]
sr-api = { git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
rstd = { package = "sr-std", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
sr-primitives = {  git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
app-crypto = { package = "substrate-application-crypto", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", default-features = false }
#slots = { package = "substrate-consensus-slots", git = "https://github.com/darwinia-network/substrate.git", branch = "darwinia-develop", optional = true }
slots = { package = "substrate-consensus-slots", path = "../../slots", optional = true }
schnorrkel = { version = "0.8.5", features = ["preaudit_deprecated"], optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }

[features]
default = ["std"]
std = [
	"rstd/std",
	"sr-primitives/std",
	"sr-api/std",
	"codec/std",
	"schnorrkel",
	"slots",
	"app-crypto/std",
]
