[package]
authors.workspace = true
description       = "Darwinia messages gadget pallet."
edition.workspace = true
name              = "dp-message-gadget"
readme            = "README.md"
version.workspace = true

[dependencies]
# crates.io
codec      = { workspace = true, package = "parity-scale-codec" }
log        = { workspace = true }
scale-info = { workspace = true }

# frontier
pallet-evm = { workspace = true }

# substrate
frame-support = { workspace = true }
frame-system  = { workspace = true }
sp-core       = { workspace = true }
sp-io         = { workspace = true }
sp-runtime    = { workspace = true, optional = true }
sp-std        = { workspace = true }

[dev-dependencies]
# crates.io
array-bytes = { workspace = true }

# substrate
pallet-balances  = { workspace = true, features = ["std"] }
pallet-timestamp = { workspace = true, features = ["std"] }

[features]
default = ["std"]

std = [
	# crates.io
	"codec/std",
	"log/std",
	"scale-info/std",

	# frontier
	"pallet-evm/std",

	# substrate
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]

try-runtime = [
	# substrate
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-evm/try-runtime",
	"sp-runtime?/try-runtime",
]
