name: "Auto author assign"

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign-author:
    name: Author assign
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.0.1
