name: Check Storage Prefix
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always
  PORT_HTTP: 9001
  PORT_WS: 9002


jobs:
  run-node:
    name: Run nodes and check storage prefix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-02-25
          override: true
          target: wasm32-unknown-unknown

      - name: Check storage prefix
        run: |
          cargo build --release
          cargo install ci-bot --git https://github.com/darwinia-network/darwinia-kit
          ci-bot storage-prefix --chain darwinia --exec ./target/release/darwinia
          ci-bot storage-prefix --chain crab --exec ./target/release/darwinia
