name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Cache darwinia target
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-darwinia-target

      - name: Overall test
        env:
          RUST_TOOLCHAIN: nightly-2021-02-25
          OVERALL_TEST: true
        run: .maintain/setup-darwinia.sh

      - uses: 8398a7/action-slack@v3
        if: failure() && (github.event_name == 'pull_request' && github.event.pull_request.draft == false || github.event_name != 'pull_request')
        with:
          status: ${{ job.status }}
          fields: repo,author,eventName,workflow,ref,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
