name: Notify release

on:
  push:
    tags:
      - "v*"
      - "pango*"

jobs:
  notify-mainnet:
    name: Notify mainnet
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: |
          TAG=$(echo ${{ github.ref }} | sed 's!.*/\(.*\)!\1!')
          curl -X POST \
            -H "Authorization:Bearer ${{ secrets.GH_TKN_DARWINIA }}" \
            -H "Accept:application/vnd.github+json" \
            "https://api.github.com/repos/darwinia-network/darwinia-releases/actions/workflows/wasm.yml/dispatches" \
            -d '{"ref":"main","inputs":{"network":"mainnet","tag":"'${TAG}'"}}'

  notify-testnet:
    name: Notify testnet
    if: startsWith(github.ref, 'refs/tags/pango')
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: |
          TAG=$(echo ${{ github.ref }} | sed 's!.*/\(.*\)!\1!')
          curl -X POST \
            -H "Authorization:Bearer ${{ secrets.GH_TKN_DARWINIA }}" \
            -H "Accept:application/vnd.github+json" \
            "https://api.github.com/repos/darwinia-network/darwinia-releases/actions/workflows/wasm.yml/dispatches" \
            -d '{"ref":"main","inputs":{"network":"testnet","tag":"'${TAG}'"}}'
