name: Pre-release
on:
  issue_comment:
    type: [created, edited]

jobs:
  pre-release:
    name: Pre release
    if: github.event.issue.pull_request && contains(github.event.comment.body, '[BOT CHECK]') && contains(github.event.comment.body, 'pre-release')
    runs-on: ubuntu-latest
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v2
      - name: Create checklist
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/checklist-template.md
