name: Release

on:
  push:
    tags:
      - "v*"
      - "pango*"

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_TERM_COLOR: always

  DOCKER_REGISTRY: ghcr.io

  GOMPLATE_VERSION: v3.11.6
  GOMPLATE: gomplate_linux-amd64
  GOMPLATE_URL: https://github.com/hairyhenderson/gomplate/releases/download/${{ env.GOMPLATE_VERSION }}/${{ env.GOMPLATE }}

  RUST_BACKTRACE: full
  RUST_TOOLCHAIN: nightly-2023-05-22

jobs:
  build-packages:
    name: Build packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact:
          - network: mainnet
            features: darwinia-native,crab-native
            bz2: true
          - network: mainnet
            features: darwinia-native,crab-native,evm-tracing
            node-type: tracing
          - network: testnet
            features: pangoro-native,pangolin-native
            bz2: true
          - network: testnet
            features: pangoro-native,pangolin-native,evm-tracing
            node-type: tracing
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: false
      - name: Set swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 8
      - name: Fetch latest code
        uses: actions/checkout@v4
      - name: Build testnet
        if: ${{ startsWith(github.ref, 'refs/tags/pango') && (matrix.artifact.network == 'testnet') }}
        uses: ./.github/actions/build
        with:
          package: darwinia
          features: ${{ matrix.artifact.features }}
          suffix: ${{ matrix.artifact.node-type }}
          enable_cache: false
          bz2: ${{ matrix.artifact.bz2 }}
      - name: Build mainnet
        if: ${{ startsWith(github.ref, 'refs/tags/v') && (matrix.artifact.network == 'mainnet') }}
        uses: ./.github/actions/build
        with:
          package: darwinia
          features: ${{ matrix.artifact.features }}
          suffix: ${{ matrix.artifact.node-type }}
          enable_cache: false
      - name: Upload ${{ matrix.artifact.network }}-${{ matrix.artifact.node-type }} node
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact.network }}-${{ matrix.artifact.node-type }}
          path: build
      - name: Fail fast
        uses: vishnudxb/cancel-workflow@v1.2
        if: failure()
        with:
          repo: darwinia-network/darwinia
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}

  build-runtimes:
    name: Build runtimes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - darwinia
          - crab
          - pangolin
          - pangoro
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v4
      - name: Setup gomplate
        run: |
          curl -LO ${{ env.GOMPLATE_URL }}
          chmod u+x ${{ env.GOMPLATE }}
          mv ${{ env.GOMPLATE }} ~/.local/bin/gomplate
      - name: Build ${{ matrix.runtime }} runtime
        uses: chevdor/srtool-actions@v0.9.1
        with:
          image: paritytech/srtool
          tag: "1.70.0"
          chain: ${{ matrix.runtime }}
      - name: Prepare artifact
        run: |
          mkdir -p build
          echo '${{ steps.srtool_build.outputs.json }}' | jq > build/${{ matrix.runtime }}-srtool.json
          cp ${{ steps.srtool_build.outputs.wasm_compressed }} build/

          export CHAIN=${{ matrix.runtime }}
          cat .github/template-runtime.md \
            | gomplate -d srtool=build/${{ matrix.runtime }}-srtool.json \
            > build/release-template-${{ matrix.runtime }}.md
      - name: Upload ${{ matrix.runtime }} runtime
        uses: actions/upload-artifact@v4
        with:
          name: artifact-runtime-${{ matrix.runtime }}
          path: build
      - name: Fail fast
        uses: vishnudxb/cancel-workflow@v1.2
        if: failure()
        with:
          repo: darwinia-network/darwinia
          workflow_id: ${{ github.run_id }}
          access_token: ${{ github.token }}

  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [build-packages]
    steps:
      - name: Download node
        uses: actions/download-artifact@v4
      - name: Tag
        uses: olegtarasov/get-tag@v2.1
      - name: Sha
        uses: benjlevesque/short-sha@v2.2
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}
      - name: Extract shared
        run: |
          mkdir -p dist
          tar -xvf build/darwinia-x86_64-linux-gnu.tar.bz2 -C dist/
      - name: Publish docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: .maintain/docker/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:sha-${{ env.SHA }}
      - name: Publish docker image with tag
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/pango')
        with:
          push: true
          context: .
          file: .maintain/docker/Dockerfile
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:${{ env.GIT_TAG_NAME }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-package, build-runtimes, build-docker-image]
    steps:
      - name: Download nodes and runtimes
        uses: actions/download-artifact@v4
      - name: Setup gomplate
        run: |
          curl -LO ${{ env.GOMPLATE_URL }}
          chmod u+x ${{ env.GOMPLATE }}
          mv ${{ env.GOMPLATE }} ~/.local/bin/gomplate
      - name: Tag
        uses: olegtarasov/get-tag@v2.1
      - name: Sha
        uses: benjlevesque/short-sha@v2.2
      - name: Prepare artifacts
        run: |
          mkdir -p deploy
          mv build/*/*.tar.bz2 deploy/
          mv build/*/*.tar.zst deploy/
      - name: Prepare release template
        run: |
          export RELEASE_SCHEMA='{"tag": "'$GIT_TAG_NAME'", "sha": "'$SHA'"}'
          cat .github/template-release.md \
            | gomplate -d schema='env:/RELEASE_SCHEMA?type=application/json' \
            > template-release.tmp.md
      - name: Fill mainnets release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mv build/*/darwinia* deploy/
          mv build/*/crab* deploy/
          cat build/release-template-darwinia.md >> template-release.md
          cat build/release-template-crab.md >> template-release.md
          cat template-release.tmp.md >> template-release.md
      - name: Fill testnets release
        if: startsWith(github.ref, 'refs/tags/pango')
        run: |
          mv build/*/pangolin* deploy/
          mv build/*/pangoro* deploy/
          cat build/release-template-pangolin.md >> template-release.md
          cat build/release-template-pangoro.md >> template-release.md
          cat template-release.tmp.md >> template-release.md
      - name: Hash file
        run: cd deploy && sha256sum * | tee sha256sums.txt
      #      - name: Verify
      #        run: |
      #          set -xe
      #          cat template-release.md
      #          ls -la deploy/
      #          cat build/*.md
      - name: Publish github release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          body_path: "template-release.md"
          files: |
            deploy/*
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pango') }}

  deploy-tracing-node:
    name: Deploy tracing node
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Tag
        uses: olegtarasov/get-tag@v2.1
      - name: Deploy mainnets' tracing node
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          GITHUB_TOKEN=${{ secrets.GH_TKN_DARWINIA }} gh workflow run \
            trigger-tracing-node.yml \
            --ref=main \
            --repo=darwinia-network/devops \
            --raw-field=type=mainnets \
            --raw-field="version=$GIT_TAG_NAME"
      - name: Deploy testnets' tracing node
        if: startsWith(github.ref, 'refs/tags/pango')
        run: |
          GITHUB_TOKEN=${{ secrets.GH_TKN_DARWINIA }} gh workflow run \
            trigger-tracing-node.yml \
            --ref=main \
            --repo=darwinia-network/devops \
            --raw-field=type=testnets \
            --raw-field="version=$GIT_TAG_NAME"

  clean-artifacts:
    name: Clean artifacts
    runs-on: ubuntu-latest
    needs: [release]
    if: always()
    steps:
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: artifact-*
