name: Release
#on:
#  push:
#    tags:
#      - 'v*'
on:
  pull_request:
    branches:
      - main
      - master

jobs:

  build-package:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt update -y
          apt install --no-install-recommends -y curl make gcc g++ clang-4.0

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-04-22
          target: wasm32-unknown-unknown
          default: true

      - name: Cache target
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-target

      - name: Build darwinia
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Collect shared
        run: |
          mkdir -p shared/crab-runtime
          mkdir -p shared/darwinia-runtime
          mv target/x86_64-unknown-linux-gnu/release/darwinia shared/
          mv target/x86_64-unknown-linux-gnu/release/wbuild/crab-runtime/*.wasm shared/crab-runtime
          mv target/x86_64-unknown-linux-gnu/release/wbuild/darwinia-runtime/*.wasm shared/darwinia-runtime

      - name: Upload deploy
        uses: actions/upload-artifact@v2
        with:
          name: darwinia-artifact
          path: shared

      - name: Optimize cache
        # todo: set executable permissions for optimize-cache.sh
        run: sh -f .maintain/optimize-cache.sh


  test-subwasm:
    name: Test subwasm
    runs-on: ubuntu-latest
    needs: [build-package]
    strategy:
      matrix:
        runtime: [crab-runtime, darwinia-runtime]
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: darwinia-artifact
          path: shared

      - name: Install subwasm
        env:
          # Currently, Same with srtool version v0.9.18
          # https://github.com/paritytech/srtool/blob/v0.9.18/Dockerfile#L19
          SUBWASM_VERSION: 0.15.0
        run: |
          curl -L https://github.com/chevdor/subwasm/releases/download/v${SUBWASM_VERSION}/subwasm_linux_amd64_v${SUBWASM_VERSION}.deb \
            --output subwasm.deb && \
            dpkg -i subwasm.deb && \
            subwasm --version

      - name: Test subwasm for ${{ matrix.runtime }}
        run: |
          WASM=$(find shared/${{ matrix.runtime }} -type f -name "*.compact.wasm")
          Z_WASM=$(find shared/${{ matrix.runtime }} -type f -name "*.compact.compressed.wasm")

          subwasm -j info $WASM
          subwasm -j info $Z_WASM

