name: Release

on:
  push:
    tags:
      - "v*"
      - "pango*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  release-testnets:
    name: Release testnets
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/pango')
    steps:
      - uses: actions/checkout@v3
      - name: Generate template data
        run: |
          echo 'Template data:'
          jq -n \
            --arg pangolin_proposal_compressed "1" \
            --arg pangolin_blake2_256_compressed "1" \
            --arg pangolin_runtime_version "1" \
            --arg pangoro_proposal_compressed "1" \
            --arg pangoro_blake2_256_compressed "1" \
            --arg pangoro_runtime_version "1" \
            --arg tag "1" \
            --arg sha "1" \
            '{
              pangolin_proposal_compressed: $pangolin_proposal_compressed,
              pangolin_blake2_256_compressed: $pangolin_blake2_256_compressed,
              pangolin_runtime_version: $pangolin_runtime_version,
              pangoro_proposal_compressed: $pangoro_proposal_compressed,
              pangoro_blake2_256_compressed: $pangoro_blake2_256_compressed,
              pangoro_runtime_version: $pangoro_runtime_version,
              tag: $tag,
              sha: $sha
            }' | tee template_data.json

      - name: Render release page
        uses: jayamanikharyono/jinja-action@v0.1
        with:
          datafile: template_data.json
          path: .github/release-testnets.md

      - name: Publish github release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          body_path: ".github/release-testnets.md"
          # generate_release_notes: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
