name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: Setup docker
#        uses: docker-practice/actions-setup-docker@master

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.QUAY_IO_BOT_USERNAME }}
          password: ${{ secrets.QUAY_IO_BOT_PASSWORD }}
          registry: quay.io

      - name: Cache darwinia target
        id: cache-target
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-darwinia

      - name: Build darwinia
        env:
          RUST_TOOLCHAIN: nightly-2020-10-06
        run: |
          sh -f .maintain/build-darwinia.sh x86_64 || exit 1
#          sh -f .maintain/build-darwinia.sh aarch64 || exit 1

      - name: Build wasm
        env:
          RUST_TOOLCHAIN: nightly-2020-10-27
        run: sh -f .maintain/setup-wasm.sh

      - name: Setup image
        run: sh -f .maintain/setup-image.sh



      - name: Complete build
        run: sh -f .maintain/complete-build.sh

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            bin/*

      - uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
          fields: repo,author,eventName,workflow,ref,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
