name: Rust docs
on:
  push:
    tags:
      - 'v*'


jobs:

  build-rust-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-04-22
          target: wasm32-unknown-unknown
          default: true

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install vercel-cli
        run: npm i -g vercel

      - name: Build rust docs
        run: cargo doc --all --no-deps --release

      - name: Deploy rust docs
        run: |
          # rename directory is required, more documents please search use keyword `vercel` in notion
          mv vercel.json target/doc
          mv target/doc target/${GITHUB_REPOSITORY#*/}
          cd target/${GITHUB_REPOSITORY#*/}
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering link --confirm
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope itering deploy --prod

