name: Release
on:
  push:
    tags:
      - 'v*'

jobs:


  complete-build:
    name: Complete build
    runs-on: ubuntu-latest
    needs: [build-subwasm, build-image]
    steps:
      - uses: actions/checkout@v2

      - name: Generate template data
        run: |
          PROPOSAL_CRAB_COMPACT=0x001
          PROPOSAL_DARWINIA_COMPACT=0x002

          IMAGE_PUSH_NAME_TAG=query.io/darwinia-network/darwinia:v0.1
          IMAGE_PUSH_NAME_SHA=query.io/darwinia-network/darwinia:sha-1234567

          JSON=$( jq -n \
            --arg crab_proposal_compact "$PROPOSAL_CRAB_COMPACT" \
            --arg darwinia_proposal_compact "$PROPOSAL_DARWINIA_COMPACT" \
            --arg image_tag "$IMAGE_PUSH_NAME_TAG" \
            --arg image_sha "$IMAGE_PUSH_NAME_SHA" \
            '{
              crab_proposal_compact: $crab_proposal_compact,
              darwinia_proposal_compact: $darwinia_proposal_compact,
              image_tag: $image_tag,
              image_sha: $image_sha
            }' )
          echo "$JSON" > shared/template_data.json

      - name: Render release page
        uses: jayamanikharyono/jinja-action@v0.1
        with:
          datafile: shared/template_data.json
          path: .maintain/release-template.md

      - name: Publish github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "deploy/*"
          bodyFile: ".maintain/release-template.md"
          token: ${{ secrets.GITHUB_TOKEN }}
